name: Mandelbrot
main: me.sablednah.Mandelbrot.Mandelbrot
version: 1.1
description: >
             Mandelbrot!

commands:
    Mandelbrot:
        description: Plot a Mandelbrot set
        usage: /<command> <width> <height|depth> [flat]